import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Manchurian Chicken',
      slug: 'Manchurian-Chicken',
      category: 'Chicken',
      image: '/images/c1.png', // 679px × 829px
      price: 85,
      countInStock: 11,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Chicken 65',
      slug: 'Chicken-65',
      category: 'Chicken',
      image: '/images/c2.png', // 679px × 829px
      price: 50,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Tandoori Chicken Platter',
      slug: 'Tandoori-Chicken-Platter',
      category: 'Chicken',
      image: '/images/c3.png', // 679px × 829px
      price: 78,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Korean Chicken',
      slug: 'Korean-Chicken',
      category: 'Chicken',
      image: '/images/c4.png', // 679px × 829px
      price: 115,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Combo Chicken, Salad and Chips',
      slug: 'Combo-Chicken-Salad-Chips',
      category: 'Chicken',
      image: '/images/c7.png', // 679px × 829px
      price: 90,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Chicken Tikka Malaysia',
      slug: 'Chicken-Tikka-Malaysia',
      category: 'Chicken',
      image: '/images/c6.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    //Soup
    {
      name: 'Butter Chicken Malaysia',
      slug: 'Butter-Chicken-Malaysia',
      category: 'Soup',
      image: '/images/cu1.png', // 679px × 829px
      price: 200,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Mixed Vegetable Curry',
      slug: 'Mixed-Vegetable-Curry',
      category: 'Soup',
      image: '/images/cu2.png', // 679px × 829px
      price: 100,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Shrimp Malaysia Curry',
      slug: 'Shrimp-Malaysia-Curry',
      category: 'Soup',
      image: '/images/cu3.png', // 679px × 829px
      price: 150,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Chicken Curry',
      slug: 'Chicken-Curry',
      category: 'Soup',
      image: '/images/cu4.png', // 679px × 829px
      price: 220,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Beef Curry',
      slug: 'Beef-Curry',
      category: 'Soup',
      image: '/images/cu5.png', // 679px × 829px
      price: 265,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Tom Yum Soup',
      slug: 'Tom-Yum-Soup',
      category: 'Soup',
      image: '/images/cu6.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    //Drinks
    {
      name: 'RedBull',
      slug: 'RedBull',
      category: 'Drinks',
      image: '/images/d1.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Pepsi',
      slug: 'Pepsi',
      category: 'Drinks',
      image: '/images/d2.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Monster Energy',
      slug: 'Monster-Energy',
      category: 'Drinks',
      image: '/images/d3.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Blue Hawaii',
      slug: 'Blue-Hawaii',
      category: 'Drinks',
      image: '/images/d4.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Sprite',
      slug: 'Sprite',
      category: 'Drinks',
      image: '/images/d5.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Fanta',
      slug: 'Fanta',
      category: 'Drinks',
      image: '/images/d6.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Mango Pana Cotta',
      slug: 'Mango-Pana-Cotta',
      category: 'Drinks',
      image: '/images/d7.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'CocaCola',
      slug: 'CocaCola',
      category: 'Drinks',
      image: '/images/d8.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    //Fish
    {
      name: 'Seafood',
      slug: 'Seafood',
      category: 'Fish',
      image: '/images/fi1.png', // 679px × 829px
      price: 350,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Fish Fry',
      slug: 'Fish-Fry',
      category: 'Fish',
      image: '/images/fi2.png', // 679px × 829px
      price: 220,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Grilled Fish',
      slug: 'Grilled-Fish',
      category: 'Fish',
      image: '/images/fi3.png', // 679px × 829px
      price: 220,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Lemon Marinated Fish',
      slug: 'Lemon-Marinated-Fish',
      category: 'Fish',
      image: '/images/fi4.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Seared Sea Bass',
      slug: 'Seared-Sea-Bass',
      category: 'Fish',
      image: '/images/fi5.png', // 679px × 829px
      price: 300,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    //Ice-cream
    {
      name: 'Sundae Chocolate',
      slug: 'Sundae-Chocolate',
      category: 'Ice-cream',
      image: '/images/i1.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Sundae Vanilla',
      slug: 'Sundae-Vanilla',
      category: 'Ice-cream',
      image: '/images/i2.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Vanilla',
      slug: 'Vanilla',
      category: 'Ice-cream',
      image: '/images/i3.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Mixed Scoop',
      slug: 'Mixed-Scoop',
      category: 'Ice-cream',
      image: '/images/i3.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'StrawBerry Scoop',
      slug: 'StrawBerry-Scoop',
      category: 'Ice-cream',
      image: '/images/i5.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Single Ice-cream',
      slug: 'Single-Ice-cream',
      category: 'Ice-cream',
      image: '/images/i6.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Sundae StrawBerry Scoop',
      slug: 'Sundae-StrawBerry-Scoop',
      category: 'Ice-cream',
      image: '/images/i7.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    //Rice
    {
      name: 'Biryani',
      slug: 'Biryani',
      category: 'Rice',
      image: '/images/r1.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Chicken Biryani',
      slug: 'Chicken-Biryani',
      category: 'Rice',
      image: '/images/r2.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Chicken Biryani(More salty)',
      slug: 'Chicken-Biryani-salty',
      category: 'Rice',
      image: '/images/r3.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Fish Biryani',
      slug: 'Fish-Biryani',
      category: 'Rice',
      image: '/images/r4.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
    {
      name: 'Tofu Biryani',
      slug: 'Tofu-Biryani',
      category: 'Rice',
      image: '/images/r5.png', // 679px × 829px
      price: 180,
      countInStock: 10,
      brand: 'nminh',
      rating: 4.5,
      numReviews: 10,
      description: 'Vị ngon đến đầu ngón tay',
    },
  ],
};
export default data;
